spring.application.name=kafka-demo

#kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#Data Generator Settings
generator.topic=sensor-data
generator.interval-ms=1000
generator.enable=true

generator.type=sensor

